
services:
  app:
    container_name: server
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      -  capstone
    depends_on:
      - client

networks:
  capstone:
    driver: bridge